### PR TITLE
List jobs on the current account.

### PR DESCRIPTION
**Pull request by smashwilson**
Use the `/jobs` API to list your job history and currently-running jobs.

Remaining Work:
- [x] Upgrade ember-cli to work with node 0.12.0.
- [x] List active and previous jobs on `/home`
- [x] Remember sessions with local or session storage.
  - [x] Persist sessions in `localStorage` if "remember me" was checked, or `sessionStorage` otherwise.
  - [x] Populate the session and redirect to `/home` if a session cookie is present.
  - [x] Delete the session storage if "logout" is used.
- [x] Fix the profile page to actually show your API key.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Trying out your branch, I hit this error on `ember server`:

```
$ ember server
version: 0.1.7
Could not find watchman, falling back to NodeWatcher for file system events
Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
    at RegExp.test (native)
    at Symbol.hasOwnProperty (/Users/kyle6475/code/frontend/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:163:43)
    at /Users/kyle6475/code/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:136:17
    at setToStringTag (/Users/kyle6475/code/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:88:13)
    at /Users/kyle6475/code/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:610:3
    at /Users/kyle6475/code/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:614:2
    at Object.<anonymous> (/Users/kyle6475/code/frontend/node_modules/ember-cli-6to5/node_modules/broccoli-6to5-transpiler/node_modules/6to5-core/node_modules/core-js/library.js:2101:2)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
```

Don't be alarmed though. Apparently the current release of iojs and ember-cli aren't compatible. https://github.com/ember-cli/ember-cli/issues/2991#issuecomment-69915182.

**Comment by rgbkrk** [comment]
Cool, I'm back to using nvm again so I just switched out to node 0.10 for now.

**Comment by smashwilson** [comment]
Hah, it's also busted on node 0.12, which was released over the weekend. I'm upgrading ember-cli presently.

**Comment by smashwilson** [comment]
Ah, looks like master is [green on 0.12, but still red on iojs](https://travis-ci.org/ember-cli/ember-cli/builds/50058651). Let's see if that's true for the latest release...

**Pull request merged**
